api_version = "2025-04"

[[extensions]]
type = "admin_action"
name = "Print Invoice - SWB Auto PDF Invoices"
handle = "print-invoice"

[[extensions.targeting]]
target = "admin.order-details.action.render"
module = "./src/index.jsx"